### ISSUE TITLE
Credentials in source

### ISSUE THREAD

**Issue by bkizer-tenable** [mguelfi/nsu#1]
Hello! I'm on the team @ Tenable. We've receive alerts when there are credentials posted that look like they could be associated with tenable. 

I was alerted about https://github.com/mguelfi/nsu/blob/8e51bad269f8d0c0b5fce7699f47712409eeca06/build/lib/tenable/io/scans.py#L358

Doesn't look like our credential, I wanted to make sure you're aware of being posted.

**Comment by mguelfi** [comment]
It's an example of what a credential might look like in the pytenable source...
